pelletier-construction-group-nextjs-8-28-home-page-component
PelletierConstructionGroup/pelletier-construction-group-nextjs pull request #29
Opened 2024-06-13 15:46 UTC by Ali-7s

Satisfies #28 
* Created homepage component with placeholder text

2024-06-13 19:15 UTC, taylorpapke requested changes
It looks like @JoyZhang2023 already created a default home page called page.tsx when she created the nav bar component.

I would say that we should either edit the page.tsx to include contents from index.tsx or redirect home page to use index.tsx. We will also need to make sure that placeholder text is displayed under the nav bar.

2024-06-14 02:07 UTC, JoyZhang2023 requested changes
@Ali-7s When I run `npm run dev` and got below page instead of home page placeholder. To be consistent with other projects structure, I suggest to update page.tsx as home page placeholder.
![image](https://github.com/PelletierConstructionGroup/pelletier-construction-group-nextjs/assets/137982978/01bbeab7-a917-4f0e-b399-ee34cda426d1)

2024-06-14 03:18 UTC, Ali-7s commented
I deleted index.tsx and updated page.tsx to be the new placeholder homepage file @taylorpapke @JoyZhang2023 
It should show like this now:
<img width="1507" alt="image" src="https://github.com/PelletierConstructionGroup/pelletier-construction-group-nextjs/assets/22021615/4aa20fec-548c-422d-9e92-04a9cc72091e">

2024-06-14 03:33 UTC, JoyZhang2023 approved these changes

2024-06-14 09:05 UTC, taylorpapke approved these changes

2024-06-14 09:05 UTC, merged