Add responsive layout to Projects page with dynamic image grid
PelletierConstructionGroup/pelletier-construction-group-nextjs pull request #60
Opened 2024-11-02 18:16 UTC by Diego-Cano

This is a pull request!

## Resolves Issue #58 

### Description

This pull request adds a responsive layout to the Projects page, making the image grid adaptable to different screen sizes (mobile, tablet, desktop). The layout is implemented using Material-UI’s `useTheme` and `useMediaQuery` hooks to ensure that images are showed in a flexible grid format that adjusts dynamically across screens.

Computer:
![LAPTOP](https://github.com/user-attachments/assets/f3359c5a-9d9b-4825-977c-20a8b11ea1ca)

Ipad:
![Ipad](https://github.com/user-attachments/assets/80844bb9-e705-4664-9577-70fdb31f732e)

Phone:
![iphone](https://github.com/user-attachments/assets/086147ea-c38e-4914-bb97-7f056d2fddfc)

2024-11-06 21:47 UTC, ken-ni commented
Great work, but it seems to scale better with smaller screens currently. On my computer screen the images are really big and you can't read the caption for each photo. I tried to improve it locally by adding a gap property to the ImageList and by modifying the spacing, but I wasn't successful. This is how it looks for me:
![Screenshot from 2024-11-06 13-32-34](https://github.com/user-attachments/assets/fa8ef511-8358-4065-ae56-40c91ba2d188)

If you would like to collaborate on this feature let me know, it would be nice to get some experience with MUI.

2024-11-07 21:50 UTC, larsswenson requested changes
Nice work! I'm also having the issue ken-ni described where the images lack padding, obscuring most of the captions, as well as being different sizes.
<img width="1655" alt="Screenshot 2024-11-07 at 1 43 31 PM" src="https://github.com/user-attachments/assets/d6dc3a60-3036-42d7-b478-83f394ee59d4">
<img width="1648" alt="Screenshot 2024-11-07 at 1 43 54 PM" src="https://github.com/user-attachments/assets/9b25a2a0-b641-49e8-bd95-f5fc73a90436">

2024-11-13 01:05 UTC, ogarmela approved these changes

2024-12-08 13:23 UTC, ogarmela approved these changes
It looks greats

2025-01-13 23:04 UTC, closed without merging