Added header image and styling to the contact page
PelletierConstructionGroup/pelletier-construction-group-nextjs pull request #70
Opened 2024-11-23 18:26 UTC by gitbiruk2010

This is a pull request!

https://github.com/PelletierConstructionGroup/pelletier-construction-group-nextjs
sprint 15
#69 
Add Header Image with Styling and Fonts Consistent with Testimonial Page to Contact Page

Please fill out this description with the following:
Resolves #69 
![contact-page without header image sprint-15](https://github.com/user-attachments/assets/30f2ae5c-e108-417e-98e3-4e20a01ca2d7)
![contact-page with header image sprint-15](https://github.com/user-attachments/assets/d5db6985-b664-4603-b54c-a0e985b8c236)
=================
**### Testimonial page**
=================
![image](https://github.com/user-attachments/assets/d1dafb83-679e-4f62-994f-ca732ee914d3)

2024-11-23 23:27 UTC, larsswenson approved these changes
Looks so much nicer, thank you and great work!

2024-11-24 04:05 UTC, JoyZhang2023 requested changes
As we migrating the old html repo to nextjs project, we're trying to duplicate the original page design. I checked the running "https://pelletierconstructiongroup.com/contact" page and it looks like this. @gitbiruk2010  I assume we're expecting a replica of this page header for this sprint. @larsswenson please correct me if the task should be otherwise.
![image](https://github.com/user-attachments/assets/cf5f121d-306d-4005-80e9-7502f1bcd416)

2024-11-24 18:57 UTC, Diego-Cano commented
This pull request significantly improves the contact page by adding a header image and consistent styling, which brings it more in line with the testimonial page. The header image gives the page a more professional and welcoming appearance, making it visually appealing and engaging for users. I like the attention to detail in maintaining the aesthetic consistency across pages. After testing, I noticed the image loads correctly, and the styling changes are applied seamlessly without breaking the layout. However, to match the live site's original design more closely, it would help to adjust the font and alignment for the header text. This would ensure a more similar look with the rest of the website.

The addition makes the contact page feel more polished and aligned with the site’s overall design goals, so great work on implementing this update. If anyone is interested in learning more about creating visually appealing contact pages, check out this resource: [How to Design an Effective Contact Page.](https://www.designrush.com/best-designs/websites/trends/best-contact-us-pages)

2024-11-24 18:57 UTC, Diego-Cano requested changes
The changes make the contact page feel more polished and engaging, so excellent work on this update! Once the minor adjustments are made, this will be a great addition to the project.

2024-11-26 04:21 UTC, gitbiruk2010 commented
@JoyZhang2023 Change request done.
@larsswenson Image used is to match the current running website contact page. however, the image is a little bit bigger and, I think it would look better if the image gets adjusted, not from within the styling but an actual cropping or reuse the same image from the current running website. i've increased the opacity overlay to 50% for the text to stand out. 

NOTE: on the assigned task, which is on the sprint 15 board, it says to refer to the testimonial page. 
I have attached with both images and let me know which one works best. Otherwise, it can be updated once we have the actual image.
### Similar to Testimonial page
![updated contact info on header B](https://github.com/user-attachments/assets/00b0b15c-4fe7-42ab-82b4-823ec6e3bae6)
### Similar to the [current running page](https://pelletierconstructiongroup.com/contact)
![updated contact info on header A](https://github.com/user-attachments/assets/7e79f68f-1380-47a0-8e33-556fcd202154)

2024-11-26 05:11 UTC, JoyZhang2023 approved these changes

2024-11-26 05:11 UTC, merged

2024-11-26 05:12 UTC, JoyZhang2023 commented
@gitbiruk2010  Looking good! Great work!  I have approved the change. It's good to go.

2024-12-12 05:42 UTC, ParysUnangst commented
Image is looking good on my end!
![image](https://github.com/user-attachments/assets/f98bae84-fe27-41ec-8507-5fa292170356)